global:
  scrape_interval: 5s # Intervalle de scraping par défaut

scrape_configs:
  # Microservice 1
  - job_name: 'user-microservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  # Microservice 2
  - job_name: 'product-microservice'
    scrape_interval: 5s # Scrape this job every 5 seconds
    static_configs:
      - targets: ['host.docker.internal:8082'] 
    metrics_path: /actuator/prometheus # Update the metrics path
